### PR TITLE
Typos in the Spanish translations

### PR DESCRIPTION
**Pull request by jcea**

### CODE REVIEW

**Comment by Razzeee** [comment]
translations are handled via and grabbed from transifex, so the label has to be fixed there. Please have a look at the wiki pages describing the translation process.

**Comment by jcea** [comment]
@Razzeee, I have joined "KODI-Addons" and "KODI-Skin", but there is no "spanish from Spain" in "kodi-main" transifex?. Only "Spanish from Argentina" and "Spanish from Mexico". What can I do?

**Comment by Razzeee** [comment]
Might be the case that `es` just ends up as `es_ES`

@alanwww1 will know

**Comment by jcea** [comment]
Nobody is helping me :-(

http://forum.kodi.tv/showthread.php?tid=308631&pid=2543676#pid2543676

Please, let me help you instead of scaring me away! :)

@alanwww1 ping!

**Comment by alanwww1** [comment]
es_ES is surely there. See:
That's odd. I do see it. Here is a direct link:
https://www.transifex.com/teamxbmc/kodi-...age/es_ES/

**Comment by jcea** [comment]
"404 Page not found".

**Comment by jcea** [comment]
Whet I try https://www.transifex.com/teamxbmc/kodi-main/language/es_ES/ I get redirected to https://www.transifex.com/teamxbmc/kodi-main/ . I don't know what else to try.

**Comment by Razzeee** [comment]
@jcea Have you requested to join the spanish team? Go to https://www.transifex.com/teamxbmc/kodi-main/ and check the top right, for a button.

**Pull request closed without merging**
